[package]
name = "goup"
version = "0.2.3"
authors = ["thinkgo <thinkgo@aliyun.com>"]
edition = "2021"
rust-version = "1.70.0"
build = "build.rs"
description = "goup is an elegant Go version manager"
keywords = [
    "goup",
    "golang",
    "version-manager",
    "tool",
    "rust"
]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/thinkgos/goup"
repository = "https://github.com/thinkgos/goup"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "goup"
path = "src/main.rs"

[build-dependencies]
version_check = "0.9"
shadow-rs = "0.24"

[dependencies]
goup-consts = {path = "./goup-consts"}
goup-version = {path = "./goup-version"}
goup-downloader = {path = "./goup-downloader"}

clap = {version = "4.4", features = ["derive", "env"]}
clap_complete = "4.4"
anyhow = "1.0"
which = "5.0"
prettytable-rs = "0.10"
dialoguer = "0.11"
self_update = {version = "0.39", default-features = false, features = ["rustls", "compression-flate2", "compression-zip-deflate"]}
shadow-rs = "0.24"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
strip = true
codegen-units = 1

[workspace]
resolver = "2"
members = [
    "goup-consts",
    "goup-version",
    "goup-downloader"
]