[workspace]
resolver = "2"
members = [
    "goup",
    "goup-version",
    "goup-downloader"
]
default-members = ["goup"]

[workspace.package]
version = "0.6.1"
authors = ["thinkgo <thinkgo@aliyun.com>"]
edition = "2021"
rust-version = "1.70.0"
description = "goup is an elegant Go version manager"
keywords = [
    "goup",
    "golang",
    "version-manager",
    "tool",
    "rust"
]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/thinkgos/goup-rs"
repository = "https://github.com/thinkgos/goup-rs"

[workspace.lints.rust]
unsafe_code = "forbid"
# unused = "allow" # for experimental dev

[profile.dev.package."*"]
opt-level = "z"

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1

