[package]
name = "goup"
version = "0.1.0"
authors = ["thinkgo <thinkgo@aliyun.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4", features = ["derive"]}
anyhow = "1"
which = "4.4"
dirs = "5"
prettytable-rs = "0.10"
ratatui = "0.23"
crossterm = "0.27"
regex = "1"
# git2 = "0.18"