[package]
name = "goup"
version = "0.1.0"
authors = ["thinkgo <thinkgo@aliyun.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4", features = ["derive", "env"]}
anyhow = "1"
which = "5"
dirs = "5"
prettytable-rs = "0.10"
dialoguer = "0.11"
regex = "1"
reqwest = { version = "0.11", features = ["blocking"] }
sha2 = "0.10"
flate2 = "1"
tar = "0.4"
zip = "0.6"
# git2 = "0.18"