[package]
name = "goup_rs"
version = "0.1.0"
authors = ["thinkgo <thinkgo@aliyun.com>"]
edition = "2021"
rust-version = "1.70.0"
description = "goup_rs is is an elegant Go version manager"
keywords = [
    "goup",
    "golang",
    "installer",
    "version-manager",
    "tool",
]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/thinkgos/goup_rs"
repository = "https://github.com/thinkgos/goup_rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
version_check = "0.9"

[dependencies]
clap = {version = "4", features = ["derive", "env"]}
clap_complete = "4"
anyhow = "1"
which = "5"
dirs = "5"
prettytable-rs = "0.10"
dialoguer = "0.11"
regex = "1"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls-native-roots"] }
sha2 = "0.10"
flate2 = "1"
tar = "0.4"
zip = "0.6"
# git2 = "0.18"