[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.fmt_check]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.clippy]
command = "cargo"
args = [
    "clippy", 
    "--all-targets", 
    "--all-features",
    "--" ,
    "-D", 
    "warnings"
]

[tasks.check]
command = "cargo"
args = ["check", "--all"]

[tasks.test]
command = "cargo"
args = ["test", "--all-features"]


[tasks.lint]
dependencies = [
    "fmt_check",
    "clippy",
    "check", 
    "test",
]