name: Question
description: Raise the bar on expectations
labels: 
  - 'question'
body:
  - type: checkboxes
    attributes:
      label: Please complete the following tasks
      options:
        - label: "I have searched the [open](https://github.com/thinkgos/goup-rs/issues) and [closed](https://github.com/thinkgos/goup-rs/issues?q=is%3Aissue+is%3Aclosed) issues"
          required: true
  - type: input
    attributes:
      label: goup version
      description: output of `goup --version`.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe your question
      description: Describe the question you want to ask.
    validations:
      required: true