[package]
name = "goup-version"
version = "0.2.1"
authors = ["thinkgo <thinkgo@aliyun.com>"]
edition = "2021"
rust-version = "1.70.0"
description = "goup-version goup version"
keywords = [
    "goup",
    "gvm",
    "goup",
    "golang",
    "installer",
    "version-manager",
    "tool",
]
license = "Apache-2.0"
readme = "../README.md"
homepage = "https://github.com/thinkgos/goup"
repository = "https://github.com/thinkgos/goup"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goup-consts = {path = "../goup-consts"}
anyhow = "1.0"
dirs = "5.0"
regex = "1.10"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls-native-roots"] }
junction = "1.0"